INSERT INTO cities (create_date, update_date, active, name, latitude, longitude, country)
VALUES (now(), now(), false, 'Tashkent', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Bukhara', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Andijan', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Fergana', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Jizzakh', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Urgench', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Namangan', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Navoiy', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Qarshi', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Guliston', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Samarkand', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Termez', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Nurafshon', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Kokand', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Margilan', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Angren', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Chirchiq', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Shahrisabz', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Olmaliq', null, null, 'Uzbekistan'),
       (now(), now(), false, 'Bekobod', null, null, 'Uzbekistan');